# Generated by Django 5.0 on 2023-12-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome do arquivo')),
                ('folder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da pasta destino')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='data de expiração do arquivo')),
                ('period_to_expiration', models.CharField(blank=True, max_length=100, null=True, verbose_name='periodo (em dias) de expiração do arquivo')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'db_table': 'tb_file',
            },
        ),
    ]
