# Generated by Django 5.0.1 on 2024-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expire_notification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
