# Generated by Django 5.0.1 on 2024-03-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_subfolder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user_root_folder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da pasta raiz'),
        ),
    ]
