# Generated by Django 5.0.1 on 2024-03-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
