# Generated by Django 5.0 on 2023-12-26 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_expiration_date', models.CharField(max_length=100, verbose_name='data de expiração do arquivo')),
                ('today_date', models.CharField(max_length=100, verbose_name='data atual')),
                ('status_notification', models.CharField(max_length=260, verbose_name='status da notificação')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'tb_notification',
            },
        ),
    ]
